name: Code Quality

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - name: Check TypeScript types
        run: npx tsc --noEmit

      - name: Run build to ensure everything compiles
        run: pnpm run build

      - name: Check for unused dependencies
        run: |
          npx depcheck --ignores="@types/*,eslint*,jest*,@testing-library/*" || echo "Dependency check completed"

      - name: Check bundle size
        run: |
          npx @next/bundle-analyzer || echo "Bundle analysis completed"
