name: Security & Dependencies

on:
  push:
    branches: [ '*' ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Run npm audit (fallback)
        run: npm audit --audit-level moderate
        continue-on-error: true

  dependencies:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Check for outdated dependencies
        run: pnpm outdated || echo "No outdated dependencies found"

      - name: Check for dependency vulnerabilities
        run: |
          if command -v npm &> /dev/null; then
            npm audit --json | jq '.metadata.vulnerabilities' || echo "No vulnerabilities found"
          else
            echo "npm not available for audit"
          fi
